### ISSUE TITLE
Code review comment

### ISSUE THREAD

**Issue by mattconway1984** [Loki-Astari/Examples#2]
https://github.com/Loki-Astari/Examples/blob/6e9e53b6b83a91bc4e4c2c304cfeec406022f61c/Version2/Socket.tpp#L14

I am curios to know why you chose to use a template here?

I can see that the idea was that scanForEnd (which a user defined function pointer - otherwise what's the point in the template) is a function to handle whenever some data was read, and it can decide if the data that was read contains all the data that is required....

So.... This is all good'n'well, but the function pointer passed in as scanForEnd MUST accept a size_t and return true/false (because the code in the templated function is written to call the function in this exact way). The use of a template here seems pointless, so I was wandering why you chose to do it (if I am missing something)?

**Comment by Loki-Astari** [comment]
Because it can accept more than a function pointer.  
You can also use a functor or a lambda.

In modern C++ it is very rarely a function pointer it will usually be a class object that acts as a function (functor) or a lambda defined on the spot. This is because the compiler can actually do a better job of optimizing functor (as all the class information is available at compile time) than it can do with optimizing through a pointer (where it needs to wait until runtime to find the function being run).

**Comment by Loki-Astari** [comment]
If you really want to review the code.
Please take a look here: https://codereview.stackexchange.com/q/131137/507

**Comment by Loki-Astari** [comment]
If you really want to review the code please go here:   
[Code Review StackExcahange](https://codereview.stackexchange.com/q/131137/507)
